title: NeuroGEARS
description: Neuroscience, Games, Interaction, Robotics
theme: jekyll-theme-cayman

twitter_username: neurogears
github_username:  neurogears
email: contact@neurogears.org
copyright: Â© 2022 NeuroGEARS Ltd.

plugins:
  - jekyll-feed
collections:
  pages:
    output: true
  jobs:
    output: true
exclude:
  - Gemfile
  - Gemfile.lock